[package]
name = "test_rqlited"
version = "0.2.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0" }
rqlite_client = { path = "../../rs_rqlite_client" }
url = { version = "2.5.0", optional = true }

[features]
url = ["dep:url"]
