name: Rust (test-all-features)

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

env:
  CARGO_TERM_COLOR: always
  RUST_MSRV_TOOLCHAIN: 1.67.0
  RUSTC_WRAPPER: "sccache"
  RQLITED_REDIRECT_OUTPUT: off
  RQLITED_TESTS_START: no
  SCCACHE_GHA_ENABLED: "true"

jobs:
  test-stable-all-features:
    runs-on: ubuntu-latest

    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false
        tool-cache: false
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v4
    - run: ./rqlite/install.sh
    - run: |
        ./rqlite/test-runner.sh
        ./test-features.sh
        ./rqlite/test-runner.sh --stop

  test-msrv-all-features:
    runs-on: ubuntu-latest

    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false
        tool-cache: false
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_MSRV_TOOLCHAIN }}
        components: clippy
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v4
    - run: ./rqlite/install.sh
    - run: |
        ./rqlite/test-runner.sh
        ./test-features.sh
        ./rqlite/test-runner.sh --stop
