name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        default: true
    - uses: actions-rs/clippy-check@v1
      with:
        toolchain: stable
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -v --all-features
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.62.0
        default: true
    - run: ./rqlite/install.sh
    - uses: actions-rs/cargo@v1
      with:
        command: install
        toolchain: stable
        args: cargo-all-features
    - uses: actions-rs/cargo@v1
      with:
        command: check-all-features
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: doc
        toolchain: stable
        args: --verbose --all-features --no-deps
    - uses: actions-rs/cargo@v1
      with:
        command: test-all-features
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: test-all-features
    - uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --verbose --all-features --no-deps
    - uses: actions-rs/cargo@v1
      with:
        command: build
        toolchain: stable
        args: --verbose --release
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release
